CREATE TABLE public.t_accounts (
	act_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	act_initial_balance numeric(38, 2) NOT NULL,
	act_status bool NULL,
	act_number varchar(255) NOT NULL,
	act_type varchar(255) NOT NULL,
	client_dni varchar(255) NOT NULL,
	client_name varchar(255) NULL
);

CREATE TABLE public.t_movements (
	mov_act_id int4 NOT NULL,
	mov_balance numeric(38, 2) NOT NULL,
	mov_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	mov_value numeric(38, 2) NOT NULL,
	mov_date timestamp(6) NOT NULL,
	mov_type varchar(255) NOT NULL
);